version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: fingerprints

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  server:
    container_name: fingerprinting-server
    build: ./server
    restart: always
    volumes:
      - "./server:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8000:8000
    links:
      - mongo

  web:
    container_name: fingerprinting-ui
    build: ./ui
    restart: always
    volumes:
      - "./ui:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    links:
      - server
